name: Check clang-format
on: [push, pull_request]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt install git make clang-format
      - name: Run formatting
        run: make format
      - name: Check diff
        run: git diff --exit-code
